---
# tasks file for mailserver

- name: "Select tasks for {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  include_tasks: "{{ distro_file }}/main.yml"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution }}"
    - "{{ ansible_os_family }}"
  loop_control:
    loop_var: distro_file
