---

gitlab_install_location: /var/srv/gitlab
gitlab_data_location: "{{ gitlab_install_location }}/data"
gitlab_config_location: "{{ gitlab_install_location }}/config"
gitlab_log_location: "{{ gitlab_install_location }}/log"

gitlab_domain: gitlab.example.com
gitlab_version: 12.1.3-ce.0

gitlab_ssh_port: 22

gitlab_smtp_address: smtp.example.com
gitlab_smtp_port: 465
gitlab_smtp_user_name: 'gitlab@example.com'
gitlab_smtp_password: "{{ lookup('passwordstore',  gitlab_domain + '/' + gitlab_smtp_user_name + ' create=true length=42') }}"
gitlab_snmp_tls: 'true'
gitlab_email_from: "{{ gitlab_smtp_user_name }}"
gitlab_email_reply_to: "{{ gitlab_smtp_user_name }}"

# gitlab_saml:
#   label: "SAML"
#   groups_attribute: "roles"
#   external_groups: "{{ gitlab_domain }}:external"
#   idp_cert_fingerprint: "<to be set>"
#   idp_sso_target_url: "https://sso.example.com"
#   issuer: "{{ gitlab_domain }}"
#   attribute_statements:
#     first_name: "first_name"
#     last_name: "last_name"
#     name: "name"
#     username: "username"
#     email: "email"
#   name_identifier_format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
