---
# tasks file for dockersock

- name: Copy to module to /tmp
  include_tasks: enabled.yml
  when:
    - ansible_selinux.status == "enabled"
    - dockersock_enabled

- name: Remove dockersock module
  command: semodule -r dockersock
  become: true
  register: dockersock_rm_result
  changed_when: "No such file' not in dockersock_rm_result.stderr"
  failed_when: "'No such file' not in dockersock_rm_result.stderr and dockersock_rm_result.rc > 0"
  when:
    - ansible_selinux.status == "enabled"
    - dockersock_enabled == false
