version: '2'
services:
  synapse:
    image: docker.io/matrixdotorg/synapse:{{ matrix_synapse_image_version }}
    cpu_shares: 256
    mem_limit: 1280mb
    memswap_limit: 1536mb
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - "/compiled:size=128K"
    environment:
      - "SYNAPSE_SERVER_NAME={{ matrix_synapse_servername }}"
{% for key, value in matrix_synapse_options.items() %}
      - "SYNAPSE_{{ key }}={{ value }}"
{% endfor %}
      - "POSTGRES_HOST=database"
      - "POSTGRES_PASSWORD={{ matrix_database_password }}"
    volumes:
      - "{{ matrix_data_location }}:/data"
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:{{ matrix_synapse_domain }}"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.referrerPolicy=no-referrer"
      - "traefik.port=8008"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}
{% if proxy_hiddenservice is defined %}
      - "traefik.frontend.headers.customResponseHeaders=alt-svc:h2={{ proxy_hiddenservice['content'] | b64decode | trim }}:443; ma=2592000"
{% endif %}

    networks:
      database:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always

  database:
    image: docker.io/postgres:{{ matrix_database_image_version }}
    mem_limit: 512mb
    memswap_limit: 768mb
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /run/postgresql:size=512K
      - /tmp:size=128K
    environment:
      - "POSTGRES_USER=synapse"
      - "POSTGRES_PASSWORD={{ matrix_database_password }}"
    volumes:
      - "{{ matrix_database_location }}:/var/lib/postgresql/data"
    networks:
      database:
    restart: always
networks:
  database:
    internal: true
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
