{{ ansible_managed | comment }}
version: '2'
services:
  database:
    image: mariadb
    mem_limit: 256mb
    memswap_limit: 512mb
    environment:
      - "MYSQL_ROOT_PASSWORD={{ mailserver_db_password }}"
    volumes:
      - "./db.conf.d/:/docker-entrypoint-initdb.d"
      - "./data:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      database:
    restart: always

  sogo:
    image: quay.io/sheogorath/sogo:4.0
    mem_limit: 512mb
    memswap_limit: 512mb
    volumes:
      - './sogo/sogo.conf:/etc/sogo/sogo.conf'
    environment:
      - "TZ={{ mailserver_timezone }}"
{% if mailserver_ssmtp is defined %}
      - "SSTMP_MAILSERVER={{ mailserver_ssmtp.mailhost}}"
      - "SSMTP_DOMAIN={{ mailserver_ssmtp.domain}}"
      - "SSMTP_AUTHUSER={{ mailserver_ssmtp.authuser}}"
      - "SSMTP_AUTHPASS={{ mailserver_ssmtp.authpass}}"
{% endif %}

    networks:
      database:
      memcache:
      frontend:
    restart: always

  memcached:
    image: memcached:1.4-alpine
    mem_limit: 64mb
    memswap_limit: 128mb
    networks:
      memcache:
    restart: always

  nginx:
    image: nginx
    mem_limit: 16mb
    memswap_limit: 32mb
    volumes_from:
      - "sogo:ro"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    labels:
      - "traefik.frontend.rule=Host:{{ mailserver_host }},smtp.{{ mailserver_domain }},imap.{{ mailserver_domain }},{{ mailserver_webmail_address }};PathPrefix:/"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}

    networks:
      frontend:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    mem_limit: 64mb
    memswap_limit: 128mb
    networks:
      database:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    labels:
      - "traefik.frontend.rule=Host:{{ mailserver_db_phpmyadmin }};PathPrefix:/"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}

    environment:
      - "PMA_HOST=database"

    restart: always

networks:
  database:
  memcache:
    internal: true
  frontend:
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
