{{ ansible_managed | comment }}
version: '2'
services:
  database:
    image: postgres:{{ codimd_postgres_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
{% if codimd_postgres_selinux_level is defined %}
    security_opt:
      - label=level:{{ codimd_postgres_selinux_level }}
{% endif %}

    tmpfs:
      - /run/postgresql:size=512K
      - /tmp:size=128K
    environment:
      - POSTGRES_USER={{ codimd_database_user }}
      - POSTGRES_PASSWORD={{ codimd_database_password }}
      - POSTGRES_DB={{ codimd_database_name }}
    volumes:
      - {{ codimd_database_location }}:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - hackmdPostgres
    restart: always
  codimd:
    image:  quay.io/codimd/server:{{ codimd_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
{% if codimd_selinux_level is defined %}
    security_opt:
      - label=level:{{ codimd_selinux_level }}
{% endif %}

    tmpfs:
      - /tmp:size=10M
      - /codimd/public/uploads:size=10M
    environment:
      - "CMD_DB_URL=postgres://{{ codimd_database_user }}:{{ codimd_database_password }}@database:5432/{{ codimd_database_name }}"
{% for key, value in codimd_options.items() %}
      - "CMD_{{ key }}={{ value }}"
{% endfor %}

    labels:
      - "traefik.frontend.rule=Host:{{ codimd_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.enable=true"
      - "traefik.port=3000"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}
{% if proxy_hiddenservice is defined %}
      - "traefik.frontend.headers.customResponseHeaders=alt-svc:h2={{ proxy_hiddenservice['content'] | b64decode | trim }}:443; ma=2592000"
{% endif %}

    networks:
      backend:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always
networks:
  backend:
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
