---
# tasks file for synapse

- name: Update default SELinux contexts
  sefcontext:
    target: '{{ item }}(/.*)?'
    setype: "container_file_t"
    state: present
  with_items:
    - "{{ matrix_database_location }}"
    - "{{ matrix_data_location }}"
  become: true


- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ matrix_install_location }}"
    - "{{ matrix_database_location }}"
    - "{{ matrix_data_location }}"
  become: true


- name: Deploy docker-compose.yml and config
  template:
    src: "docker-compose.yml"
    dest: "{{ matrix_install_location }}/docker-compose.yml"
    mode: 0600
    owner: 'root'
    group: 'root'
  tags:
    - docker
    - matrix
  become: true


- name: Compose synapse
  docker_compose:
    state: present
    project_src:  "{{ matrix_install_location }}"
    pull: yes
  tags:
    - docker
    - matrix
  become: true
