galaxy_info:
  author: Christoph Kern
  description: Installs and manage minio instances for S3 compatible storage
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies:
  - docker
  - docker-compose
