---

- name: Install ssh keys
  authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.key }}"
    comment: "{{ item.owner }} - {{ item.comment }} | Managed by Ansible"
  with_items:
    - "{{ ssh_authorized_keys }}"
  become: true
  tags:
    - ssh

- name: Set ratelimit for SSH
  firewalld:
    rich_rule: "rule service name=ssh limit value=10/m accept"
    state: enabled
    permanent: true
    immediate: true
  become: true
  tags:
    - firewall
    - ssh

- name: Disable SSH by firewall to let ratelimit kick in
  firewalld:
    service: "ssh"
    state: disabled
    permanent: true
    immediate: true
  become: true
  tags:
    - firewall
    - ssh
