galaxy_info:
  author: Christoph Kern
  description: Installs haveged on centos
  issue_tracker_url: https://octo.sh/Sheogorath/ansible-infrastructure/issues
  license: GPLv3
  min_ansible_version: 2.1
  platforms:
   - name: CentOS
     versions:
       - 7

  galaxy_tags: []
dependencies: []
