{{ ansible_managed | comment }}
version: '2'
services:
  mumble:
    image: sheogorath/murmur-docker:{{ mumble_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    environment:
      - "MUMBLE_REGISTERHOSTNAME={{ mumble_domain }}"
      - "MUMBLE_DEFAULTCHANNEL={{ mumble_defaultchannel }}"
      - "MUMBLE_REGISTERNAME={{ mumble_registername }}"
      - "MUMBLE_TEXTLENGTH={{ mumble_textlength }}"
      - "MUMBLE_BANDWIDTH={{ mumble_bandwidth }}"
    volumes:
      - "{{ mumble_data_location }}:/data"
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    restart: always

{% if mumble_websocket_domain is defined %}
  websockify:
    image: efrecon/websockify
    mem_limit: 64mb
    memswap_limit: 128mb
    labels:
      - "traefik.frontend.rule=Host:{{ mumble_websocket_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.port=80"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}

    restart: always
    command: --ssl-target 80 mumble:64738
{% endif %}

{% if mumble_webend_domain is defined %}
  webend:
    image: sheogorath/mumble-web
    mem_limit: 32mb
    mem_limit: 64mb
    labels:
      - "traefik.frontend.rule=Host:{{ mumble_webend_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.port=80"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}

    restart: always
{% endif %}

{% for bot in mumble_bots %}
  {{ bot.mumblechannel }}:
    image: sheogorath/docker-sftmumblebot:latest
    mem_limit: 32mb
    mem_limit: 64mb
    environment:
      - "BOT_IRC_SERVER={{ bot.ircserver }}"
      - "BOT_IRC_CHANNEL={{ bot.ircchannel }}"
      - "BOT_MUMBLE_CHANNEL=#{{ bot.mumblechannel }}"
      - "BOT_MUMBLE_SERVER=mumble"
      - "BOT_BOTNAME={{ bot.name }}"
    restart: always
{% endfor %}
