galaxy_info:
  author: Christoph Kern
  description: Backup of LVM volumes with duplicity crypted with GPG
  issue_tracker_url: https://octo.sh/Sheogorath/ansible-infrastructure/issues
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: CentOS
      versions:
        - 7
  galaxy_tags: []
dependencies: []
