version: '2'
services:
  dns:
    image: secns/unbound
    mem_limit: 128mb
    memswap_limit: 256mb
    security_opt:
      - no-new-privileges
    networks:
      internal:
    restart: always
  doh:
    image: quay.io/sheogorath/doh:{{ doh_version }}
    mem_limit: 128mb
    memswap_limit: 256mb
    security_opt:
      - no-new-privileges
    environment:
      - "UPSTREAM_NAME=dns"
    labels:
      - "traefik.frontend.rule=Host:{{ doh_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.port=8053"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}
{% if proxy_hiddenservice is defined %}
      - "traefik.frontend.headers.customResponseHeaders=alt-svc:h2={{ proxy_hiddenservice['content'] | b64decode | trim }}:443; ma=2592000"
{% endif %}

    networks:
      internal:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always

networks:
  internal:
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
