galaxy_info:
  author: Christoph Kern
  description: Installs ssh to preboot environment to unlock luks via ssh
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: CentOS
      versions:
        - 7
  galaxy_tags: []
dependencies:
