---

- name: Update htaccess
  shell: docker exec -u 33 nextcloud_nextcloud_1 php ./occ maintenance:update:htaccess
  args:
    chdir: "{{ nextcloud_install_location }}"
    warn: false
  become: true
