---
# tasks file for mastodon

- name: Update default SELinux contexts
  sefcontext:
    target: '{{ item }}(/.*)?'
    setype: "container_file_t"
    state: present
  with_items:
    - "{{ mastodon_database_location }}"
    - "{{ mastodon_public_location }}"
    - "{{ mastodon_redis_location }}"
  become: true


- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mastodon_install_location }}"
    - "{{ mastodon_database_location }}"
    - "{{ mastodon_public_location }}"
    - "{{ mastodon_redis_location }}"
  become: true

- name: Check if migration is needed
  command: "grep -q 'tootsuite/mastodon:{{ mastodon_image_version }}' '{{ mastodon_install_location }}/docker-compose.yml'"
  register: mastodon_version_fact
  ignore_errors: yes
  changed_when: mastodon_version_fact.rc > 0
  failed_when: false
  become: true

- name: Pull an mastodon image
  docker_image:
    name: "tootsuite/mastodon:{{ mastodon_image_version }}"
  become: true
  when:
    - mastodon_version_fact is changed

- name: Stop mastodon for upgrade
  docker_compose:
    state: present
    project_src:  "{{ mastodon_install_location }}"
    stopped: yes
  tags:
    - docker
    - mastodon
  become: true
  when:
    - mastodon_version_fact is changed

- name: Deploy config
  template:
    src: "env_config"
    dest: "{{ mastodon_install_location }}/env_config"
    mode: 0600
    owner: 'root'
    group: 'root'
  tags:
    - docker
    - mastodon
  become: true

- name: Deploy docker-compose.yml
  template:
    src: "docker-compose.yml"
    dest: "{{ mastodon_install_location }}/docker-compose.yml"
    mode: 0600
    owner: 'root'
    group: 'root'
    validate: python2 -m compose -f %s config -q
  tags:
    - docker
    - mastodon
  become: true



- name: Migrate database
  command: docker-compose run --rm web rails db:migrate
  args:
    chdir: "{{ mastodon_install_location }}"
  when:
    - mastodon_version_fact is changed
  become: true
  environment:
    PYTHONPATH:

- name: Clear cache
  command: docker-compose run --rm web bin/tootctl cache clear
  args:
    chdir: "{{ mastodon_install_location }}"
  when:
    - mastodon_version_fact is changed
  become: true
  environment:
    PYTHONPATH:

- name: Compose mastodon
  docker_compose:
    state: present
    project_src:  "{{ mastodon_install_location }}"
    pull: yes
  tags:
    - docker
    - mastodon
  become: true
