version: '2'
services:
  keycloak:
    image: jboss/keycloak:{{ keycloak_image_version }}
    mem_limit: 1gb
    memswap_limit: 1280mb
    security_opt:
      - no-new-privileges
    labels:
      - "traefik.frontend.rule=Host:{{ keycloak_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.enable=true"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}
{% if proxy_hiddenservice is defined %}
      - "traefik.frontend.headers.customResponseHeaders=alt-svc:h2={{ proxy_hiddenservice['content'] | b64decode | trim }}:443; ma=2592000"
{% endif %}

    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME={{ keycloak_domain }}
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_USER={{ keycloak_database_user }}
      - DB_PASSWORD={{ keycloak_database_password }}
    networks:
      backend:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.scripts=enabled"]
    restart: always

  database:
    image: postgres:{{ keycloak_postgres_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
{% if keycloak_postgres_selinux_level is defined %}
    security_opt:
      - label=level:{{ keycloak_postgres_selinux_level }}
{% endif %}
    tmpfs:
      - /run/postgresql:size=512K
      - /tmp:size=128K
    environment:
      - POSTGRES_USER={{ keycloak_database_user }}
      - POSTGRES_PASSWORD={{ keycloak_database_password }}
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always

networks:
  backend:
    internal: true
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
