{{ ansible_managed | comment }}
version: '2'
services:
  database:
    image: postgres:{{ hackmd_postgres_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
    tmpfs:
      - /run/postgresql:size=512K
      - /tmp:size=128K
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - {{ hackmd_database_location }}:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - hackmdPostgres
    restart: always
  hackmd:
    image:  hackmdio/hackmd:{{ hackmd_image_version }}
    mem_limit: 256mb
    memswap_limit: 512mb
    read_only: true
    tmpfs:
      - /tmp:size=10M
      - /hackmd/tmp:size=1M
      - /hackmd/public/uploads:size=10M
    environment:
      - "HMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd"
{% for key, value in hackmd_options.iteritems() %}
      - "HMD_{{ key }}={{ value }}"
{% endfor %}

    labels:
      - "traefik.frontend.rule=Host:{{ hackmd_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.enable=true"
      - "traefik.port=3000"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}

    networks:
      backend:
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always
networks:
  backend:
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
