{{ ansible_managed | comment }}
version: '2'
services:
  runner:
    image: gitlab/gitlab-runner:latest
    mem_limit: 128mb
    memswap_limit: 256mb
    volumes:
      - "./config:/etc/gitlab-runner"
    restart: always
