---
# tasks file for mumble
#

- name: Update default SELinux contexts
  sefcontext:
    target: '{{ item }}(/.*)?'
    setype: "svirt_sandbox_file_t"
    state: present
  with_items:
    - "{{ mumble_data_location }}"
  become: true


- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    setype: "svirt_sandbox_file_t"
  with_items:
    - "{{ mumble_install_location }}"
    - "{{ mumble_data_location }}"
  become: true


- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ mumble_install_location }}/docker-compose.yml"
    mode: 0600
    owner: 'root'
    group: 'root'
    validate: docker-compose -f %s config -q
  register: docker_compose_yml
  tags:
    - docker
    - mumble
  become: true

- name: Compose mumble
  docker_compose:
    state: present
    project_src:  "{{ mumble_install_location }}"
    pull: yes
  tags:
    - docker
    - mumble
  become: true
