version: '2'
services:
  database:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_USER: {{ awx_database_user }}
      POSTGRES_PASSWORD: {{ awx_database_password }}
      POSTGRES_DB: awx
    volumes:
      - "{{ awx_database_location }}:/var/lib/postgresql/data"
    networks:
      database:
    restart: always

  rabbitmq:
    image: "rabbitmq:3-alpine"
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_DEFAULT_USER: {{ awx_rabbitmq_user }}
      RABBITMQ_DEFAULT_PASS: {{ awx_rabbitmq_password }}
    networks:
      backend:
    restart: always

  memcached:
    image: "memcached:alpine"
    networks:
      backend:
    restart: always

  web:
    image: "ansible/awx_web:{{ awx_version }}"
    hostname: awxweb
    user: root
    labels:
      - "traefik.frontend.rule=Host:{{ awx_domain }};PathPrefix:/"
      - "traefik.frontend.headers.STSSeconds=63072000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.enable=true"
      - "traefik.port=8052"
{% if proxy_network is defined %}
      - "traefik.docker.network={{ proxy_network }}"
{% endif %}
    environment:
      SECRET_KEY: {{ awx_secret_key }}
      DATABASE_USER: {{ awx_database_user }}
      DATABASE_PASSWORD: {{ awx_database_password }}
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      RABBITMQ_USER: {{ awx_rabbitmq_user }}
      RABBITMQ_PASSWORD: {{ awx_rabbitmq_password }}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: {{ awx_admin_user }}
      AWX_ADMIN_PASSWORD: {{ awx_admin_password }}
    volumes:
      - "{{ awx_projects_location }}:/var/lib/awx/projects"
    depends_on:
      - rabbitmq
      - memcached
      - database
    networks:
      database:
      backend:
         aliases:
           - awxweb
{% if proxy_network is defined %}
      {{ proxy_network }}:
{% endif %}

    restart: always

  task:
    image: "ansible/awx_task:{{ awx_version }}"
    hostname: awx
    user: root
    environment:
      SECRET_KEY: {{ awx_secret_key }}
      DATABASE_USER: {{ awx_database_user }}
      DATABASE_PASSWORD: {{ awx_database_password }}
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      RABBITMQ_USER: {{ awx_rabbitmq_user }}
      RABBITMQ_PASSWORD: {{ awx_rabbitmq_password }}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: {{ awx_admin_user }}
      AWX_ADMIN_PASSWORD: {{ awx_admin_password }}
    volumes:
      - "{{ awx_projects_location }}:/var/lib/awx/projects"
    depends_on:
      - rabbitmq
      - memcached
      - database
      - web
    networks:
      database:
      backend:
    restart: always

networks:
  database:
  backend:
{% if proxy_network is defined %}
  {{ proxy_network }}:
    external: true
{% endif %}
