---
# defaults file for hackmd

codimd_database_user: codimd
codimd_database_password: codimdpass
codimd_database_name: codimd

codimd_install_location: /var/srv/codimd
codimd_database_location: "{{ codimd_install_location }}/database"

codimd_domain: pad.example.com
codimd_options:
  ALLOW_FREE_URL: false
  HMD_DOMAIN: "{{ codimd_domain }}"
  EMAIL: false
  PROTOCOL_USESSL: true
  URL_ADDPORT: false
  USECDN: true

codimd_version: 1.4.0
codimd_postgres_version: 11.2

codimd_image_version: "{{ codimd_version }}"
codimd_postgres_image_version: "{{ codimd_postgres_version }}-alpine"

#codimd_selinux_level: None
#codimd_postgres_selinux_level: None
