---
# tasks file for traefik

- name: Update default SELinux contexts
  sefcontext:
    target: '{{ item }}(/.*)?'
    setype: "container_file_t"
    selevel: "{{ traefik_selinux_level | default(omit) }}"
    state: present
  with_items:
    - "{{ traefik_acme_location }}"
  become: true

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_location }}"
    - "{{ traefik_acme_location }}"
  become: true


- name: Create proxy network
  docker_network:
    name: "{{ proxy_network }}"
    driver_options:
      com.docker.network.bridge.name: "{{ traefik_docker_bridge_name }}"
  become: true

- name: Trust our proxy network
  firewalld:
    zone: trusted
    interface: "docker-proxy"
    permanent: true
    state: enabled
  become: true

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ traefik_install_location }}/docker-compose.yml"
    mode: 0600
    owner: 'root'
    group: 'root'
  register: docker_compose_yml
  tags:
    - docker
  become: true

- name: Compose traefik
  docker_service:
    state: present
    project_src: "{{ traefik_install_location }}"
    pull: yes
  become: true

- name: Allow access to services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  become: true
  tags:
    - firewall

- name: Allow access to services
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
  with_items:
    - 8080
  become: true
  when:
    - traefik_debug is defined and traefik_debug

- name: Deny access to services
  firewalld:
    port: "{{ item }}/tcp"
    state: disabled
    immediate: true
  with_items:
    - 8080
  become: true
  when:
    - traefik_debug is not defined or not traefik_debug
