---
# tasks for sogo, the mysql db and more running on docker

# SELinux configs
- name: Update default SELinux contexts for containers
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "container_file_t"
    state: present
  with_items:
    - "/var/srv/mailserver/data"
    - "/var/srv/mailserver/db.conf.d"
    - "/var/srv/mailserver/sogo"
    - "/var/srv/mailserver/nginx"
  become: true
  tags:
    - selinux

- name: Update default SELinux contexts for postfix TLS
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "postfix_etc_t"
    state: present
  with_items:
    - "/var/srv/mailserver/ssl"
  become: true
  tags:
    - selinux

- name: Deploy sogo.conf
  template:
    src: sogo/sogo.conf
    dest: "/var/srv/mailserver/sogo/sogo.conf"
    setype: "container_file_t"
  become: true
  tags:
    - sogo

- name: Deploy nginx.conf
  template:
    src: nginx/nginx.conf
    dest: "/var/srv/mailserver/nginx/nginx.conf"
    setype: "container_file_t"
  become: true
  tags:
    - sogo-nginx

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "/var/srv/mailserver/docker-compose.yml"
  become: true
  tags:
    - docker
    - sogo
    - nginx
    - database
    - dovecot
    - postfix

- name: Compose mailserver docker
  docker_service:
    state: present
    project_src:  "/var/srv/mailserver/"
    pull: yes
  become: true
  tags:
    - docker
    - sogo
    - nginx
    - database
    - dovecot
    - postfix
