---
# tasks for sogo, the mysql db and more running on docker

# SELinxu configs
- name: Update default SELinux contexts for containers
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "container_file_t"
    state: present
  with_items:
    - "/var/srv/mailserver/data"
    - "/var/srv/mailserver/db.conf.d"
    - "/var/srv/mailserver/sogo"
    - "/var/srv/mailserver/nginx"
  become: true

- name: Update default SELinux contexts for postfix TLS
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "postfix_etc_t"
    state: present
  with_items:
    - "/var/srv/mailserver/ssl"
  become: true

- name: Deploy sogo.conf
  template:
    src: sogo/sogo.conf
    dest: "/var/srv/mailserver/sogo/sogo.conf"
    setype: "container_file_t"
  become: true

- name: Deploy nginx.conf
  template:
    src: nginx/nginx.conf
    dest: "/var/srv/mailserver/nginx/nginx.conf"
    setype: "container_file_t"
  become: true

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "/var/srv/mailserver/docker-compose.yml"
  become: true

- name: Compose mailserver docker
  docker_service:
    state: present
    project_src:  "/var/srv/mailserver/"
    pull: yes
  become: true

- name: Install export.sh
  copy:
    src: export/script.sh
    dest: /var/srv/mailserver/export.sh
    mode: 0755
  become: true

- name: Install systemd service
  copy:
    src: export/systemd.{{ item }}
    dest: /etc/systemd/system/export.{{ item }}
    seuser: system_u
    setype: systemd_unit_file_t
    serole: object_r
    mode: 0644
  with_items:
    - service
    - timer
  become: true

- name: run export.sh
  command: /var/srv/mailserver/export.sh
  args:
    creates: /var/srv/mailserver/ssl/fullchain.pem
  become: true

- name: Enable export.timer
  systemd:
    name: export.timer
    state: started
    enabled: true
  become: true
